# How to setup
# Build docker image
# > docker build -f Dockerfile_AVX -t tensor-plus .
# See image just created
# > docker images
# docker image -> docker container
# > docker run --rm -it tensor-plus

FROM tensorflow/tensorflow:1.13.1-gpu-py3-jupyter
LABEL maintainer="hamling-ling"

RUN apt-get update
RUN apt-get install -y libsndfile1-dev
RUN pip install --upgrade pip
RUN pip install seaborn keras
RUN pip install pysoundfile

