# How to setup
# Place tensorflow whl binary to Dockerfile directory
# 
# Build docker image
# > docker build -f Dockerfile_NonAVX_Tf1 --build-arg user=$USER --build-arg pass=<YOUR PASSWD> -t tensor-plus .
# See image just created
# > docker images
# docker image -> docker container
# > docker run --rm -it tensor-plus
#
# ref
#   https://qiita.com/yamanaka1213/items/c32dbe262dacde97d685

FROM tensorflow/tensorflow:1.15.2-gpu-py3-jupyter
ARG user="tfadmin"
ARG pass="tfadmin"
LABEL maintainer="hamling-ling"

RUN apt-get update
RUN apt-get install -y libsndfile1-dev
RUN apt-get install -y git
RUN apt-get install -y sudo

RUN pip install --upgrade pip

# in my case
RUN pip uninstall tensorflow
ARG TFWHL="tensorflow-1.15.2-cp36-cp36m-linux_x86_64.whl"
ADD ${TFWHL} /tmp/${TFWHL}

RUN pip install /tmp/${TFWHL}
RUN pip install seaborn keras
RUN pip install pysoundfile
RUN pip install pillow

# User
RUN echo ${user}
RUN groupadd --gid 1000 ${user}
RUN useradd -u 1000 -g 1000 -G sudo -s /bin/bash -d /home/${user} -m ${user}

RUN echo ${user}:${pass} | chpasswd
RUN echo 'Defaults visiblepw' >> /etc/sudoers
RUN echo ${user}" ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ${user}
WORKDIR /home/${user}

RUN jupyter notebook --generate-config
RUN echo "c.NotebookApp.password=''" >> ~/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.token=''" >> ~/.jupyter/jupyter_notebook_config.py 
RUN echo "c.NotebookApp.ip='0.0.0.0'" >> ~/.jupyter/jupyter_notebook_config.py 
RUN echo "c.NotebookApp.open_browser=False" >> ~/.jupyter/jupyter_notebook_config.py 
RUN echo "c.NotebookApp.port=8888" >> ~/.jupyter/jupyter_notebook_config.py
