# How to setup
# Build docker image
# > docker build -f Dockerfile_AVX --build-arg user=$USER --build-arg pass=<YOUR PASSWD> -t tensor-plus .
# See image just created
# > docker images
# docker image -> docker container
# > docker run --rm -it tensor-plus

FROM tensorflow/tensorflow:1.15.5-gpu-py3-jupyter
ARG user="tfadmin"
ARG pass="tfadmin"
LABEL maintainer="hamling-ling"

RUN apt-get update
RUN apt-get install -y libsndfile1-dev
RUN pip install --upgrade pip
RUN pip install seaborn keras
RUN pip install pysoundfile

# User
RUN echo ${user}
RUN groupadd --gid 1000 ${user}
RUN useradd -u 1000 -g 1000 -G sudo -s /bin/bash -d /home/${user} -m ${user}

RUN echo ${user}:${pass} | chpasswd
RUN echo 'Defaults visiblepw' >> /etc/sudoers
RUN echo ${user}" ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ${user}
WORKDIR /home/${user}

RUN jupyter notebook --generate-config
RUN echo "c.NotebookApp.password=''" >> ~/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.token=''" >> ~/.jupyter/jupyter_notebook_config.py 
RUN echo "c.NotebookApp.ip='0.0.0.0'" >> ~/.jupyter/jupyter_notebook_config.py 
RUN echo "c.NotebookApp.open_browser=False" >> ~/.jupyter/jupyter_notebook_config.py 
RUN echo "c.NotebookApp.port=8888" >> ~/.jupyter/jupyter_notebook_config.py
