# How to setup
# Build docker image
# > docker build -f Dockerfile_cuda10 -t tensor-plus .
# See image just created
# > docker images
# docker image -> docker container
# > docker run --rm -it tensor-plus

#use nvidia tensorflow until googles one supports cuda10
#FROM tensorflow/tensorflow:nightly-gpu-py3
FROM nvcr.io/nvidia/tensorflow:19.01-py3

LABEL maintainer="hamling-ling"

RUN apt-get update
RUN apt-get install -y libsndfile1-dev
RUN pip install --upgrade pip
RUN pip install seaborn keras
RUN pip install pysoundfile
RUN pip install requests

RUN mkdir -p /notebooks
