# How to setup
# Build docker image
# > docker build -t tensor-plus .
# See image just created
# > docker images
# docker image -> docker container
# > docker run -rm -it tensor-plus

FROM tensorflow/tensorflow:1.4.0-gpu-py3
LABEL maintainer="hamling-ling"

RUN pip install seaborn
